In [1]:
import pandas as pd
import numpy as np

# Header = ["Point ID", "Cell ID", "Cell Boundary IDs", "Status Point", "Status Boundary"]
df = pd.read_csv("saved_data/status.csv")
df.head()

,Point ID,Cell ID,Cell Boundary IDs,Status Point,Status Boundary
0,2415791,2345951,[2415755 2415756 2415762 2415761 2415791 24157...,1.625,"[1.5, 0.875, 2.375, 3.0, 1.625, 1.0, 2.5, 2.875]"
1,2415791,2345951,[2415755 2415756 2415762 2415761 2415791 24157...,1.625,"[1.5, 0.875, 2.375, 3.0, 1.625, 1.0, 2.5, 2.875]"
2,2427673,2357833,[2427637 2427638 2427644 2427643 2427673 24276...,1.875,"[1.625, 1.0, 2.5, 3.0, 1.875, 1.125, 2.625, 3.0]"
3,2427674,2357834,[2427638 2427639 2427645 2427644 2427674 24276...,1.125,"[1.0, 0.25, 1.75, 2.5, 1.125, 0.375, 1.875, 2...."
4,2427682,2357841,[2427645 2427646 2427652 2427651 2427681 24276...,0.875,"[1.75, 1.0, 2.5, 3.0, 1.875, 0.875, 2.375, 3.0]"

In [2]:
# Find duplicates (points in same cell)
len(df[df.duplicated(subset=['Cell ID'], keep=False) == True])

32

In [3]:
# Points without duplicates
df[df.duplicated(subset=['Cell ID'], keep=False) == False]

,Point ID,Cell ID,Cell Boundary IDs,Status Point,Status Boundary
2,2427673,2357833,[2427637 2427638 2427644 2427643 2427673 24276...,1.875,"[1.625, 1.0, 2.5, 3.0, 1.875, 1.125, 2.625, 3.0]"
3,2427674,2357834,[2427638 2427639 2427645 2427644 2427674 24276...,1.125,"[1.0, 0.25, 1.75, 2.5, 1.125, 0.375, 1.875, 2...."
4,2427682,2357841,[2427645 2427646 2427652 2427651 2427681 24276...,0.875,"[1.75, 1.0, 2.5, 3.0, 1.875, 0.875, 2.375, 3.0]"
5,2427682,2357842,[2427646 2427647 2427653 2427652 2427682 24276...,0.875,"[1.0, 0.25, 1.75, 2.5, 0.875, 0.125, 1.625, 2...."
6,2427690,2357849,[2427653 2427654 2427660 2427659 2427689 24276...,1.125,"[1.75, 1.0, 2.5, 3.0, 1.625, 1.125, 2.625, 3.0]"
7,2427690,2358060,[2427654 2427865 2427871 2427660 2427690 24279...,1.125,"[1.0, 0.25, 1.75, 2.5, 1.125, 0.375, 1.875, 2...."
8,2427907,2358067,[2427871 2427872 2427878 2427877 2427907 24279...,1.875,"[1.75, 0.75, 2.25, 3.0, 1.875, 0.75, 2.25, 3.0]"
9,2427908,2358068,[2427872 2427873 2427879 2427878 2427908 24279...,0.750,"[0.75, 0.0, 1.0, 2.25, 0.75, 0.0, 1.125, 2.25]"
10,2427915,2358470,[2427878 2427879 2428281 2428280 2427914 24279...,1.125,"[2.25, 1.0, 2.5, 3.0, 2.25, 1.125, 2.625, 3.0]"
11,2428318,2358472,[2427880 2427881 2428283 2428282 2427916 24279...,1.875,"[0.25, 0.0, 0.875, 1.75, 0.375, 0.0, 0.75, 1.875]"
12,2428318,2358478,[2428282 2428283 2428289 2428288 2428318 24283...,1.875,"[1.75, 0.875, 2.375, 3.0, 1.875, 0.75, 2.25, 3.0]"
13,2428319,2358479,[2428283 2428284 2428290 2428289 2428319 24283...,0.750,"[0.875, 0.125, 1.125, 2.375, 0.75, 0.0, 1.125,..."
14,2428326,2358485,[2428289 2428290 2428296 2428295 2428325 24283...,1.125,"[2.375, 1.125, 2.5, 3.0, 2.25, 1.125, 2.625, 3.0]"
15,2428326,2359992,[2428290 2429797 2429803 2428296 2428326 24298...,1.125,"[1.125, 0.25, 1.75, 2.5, 1.125, 0.375, 1.875, ..."
16,2429839,2359999,[2429803 2429804 2429810 2429809 2429839 24298...,1.875,"[1.75, 0.75, 2.25, 3.0, 1.875, 0.75, 2.25, 3.0]"
17,2429846,2360000,[2429804 2429805 2429811 2429810 2429840 24298...,2.250,"[0.75, 0.0, 0.75, 2.25, 0.75, 0.0, 0.75, 2.25]"
18,2429846,2360006,[2429810 2429811 2429817 2429816 2429846 24298...,2.250,"[2.25, 0.75, 2.25, 3.0, 2.25, 0.75, 2.25, 3.0]"
19,2429847,2360007,[2429811 2429812 2429818 2429817 2429847 24298...,0.750,"[0.75, 0.0, 0.75, 2.25, 0.75, 0.0, 0.75, 2.25]"
20,2429854,2360013,[2429817 2429818 2429824 2429823 2429853 24298...,0.750,"[2.25, 0.75, 2.25, 3.0, 2.25, 0.75, 2.25, 3.0]"
25,2614706,2539717,[2614670 2614671 2614677 2614676 2614706 26147...,1.250,"[1.0, 0.0, 0.25, 1.75, 1.25, 0.0, 0.375, 1.875]"
26,2614712,2539723,[2614676 2614677 2614683 2614682 2614712 26147...,1.875,"[1.75, 0.25, 1.0, 2.5, 1.875, 0.375, 1.125, 2...."
27,2617713,2542718,[2614683 2614684 2617678 2617677 2614719 26147...,1.875,"[1.0, 0.0, 0.25, 1.75, 1.125, 0.0, 0.375, 1.875]"
30,2617720,2542730,[2617683 2617684 2617690 2617689 2617719 26177...,1.125,"[2.5, 1.0, 1.75, 3.0, 2.625, 1.125, 1.875, 3.0]"
31,2617726,2542731,[2617684 2617685 2617691 2617690 2617720 26177...,1.875,"[1.0, 0.0, 0.25, 1.75, 1.125, 0.0, 0.375, 1.875]"
32,4682231,4562992,[4682195 4682196 4682202 4682201 4682231 46822...,2.250,"[2.0, 0.5, 0.5, 2.0, 2.25, 0.75, 0.75, 2.25]"
33,4682243,4563400,[4682207 4682208 4682610 4682609 4682243 46822...,1.875,"[1.75, 0.25, 0.0, 1.0, 1.875, 0.375, 0.0, 1.125]"
38,1739249,5766587,[1739243 1739244 1739250 1739249 5911757 59117...,1.500,"[0.75, 1.125, 1.875, 1.5, 1.5, 1.75, 2.125, 2.0]"
39,1836649,5863554,[1835136 1836643 1836649 1835142 6008484 60099...,0.750,"[2.25, 2.25, 0.75, 0.75, 2.25, 2.25, 1.25, 1.25]"
40,1836649,5863561,[1836649 1836650 1836656 1836655 6009960 60099...,0.750,"[0.75, 1.375, 0.25, 0.0, 1.25, 1.875, 0.75, 0.25]"
43,1867975,5894886,[1867764 1867975 1867981 1867770 6041310 60415...,1.500,"[0.75, 1.5, 1.5, 0.75, 1.5, 2.0, 2.0, 1.5]"
44,3812086,7787458,[3812086 3812087 3812093 3812092 7963870 79638...,1.500,"[1.5, 1.5, 0.75, 0.75, 2.0, 2.0, 1.5, 1.5]"
45,3906367,7881860,[3906361 3906362 3906368 3906367 8059609 80596...,0.750,"[0.0, 0.0, 1.125, 0.75, 0.5, 0.5, 1.625, 1.5]"
46,3906370,7881862,[3906363 3906364 3906370 3906369 8059611 80596...,2.250,"[0.375, 0.75, 2.25, 1.875, 1.0, 1.5, 2.25, 2.0]"
47,3906367,7881866,[3906367 3906368 3906374 3906373 8059615 80596...,0.750,"[0.75, 1.125, 2.625, 2.25, 1.5, 1.625, 2.375, ..."
48,3917230,7892674,[3917229 3917230 3917236 3917235 8070423 80704...,1.000,"[0.375, 1.0, 2.5, 1.875, 1.25, 1.5, 2.375, 2.0]"
49,3918934,7894372,[3918531 3918532 3918934 3918933 8071725 80717...,1.500,"[1.5, 1.5, 1.5, 1.5, 2.0, 2.0, 2.0, 2.0]"
50,4598884,8714535,[4598877 4598878 4598884 4598883 8897572 88975...,0.750,"[2.625, 2.25, 0.75, 1.125, 2.75, 2.5, 1.0, 1.25]"
53,4607962,8728798,[4607956 4607957 4607963 4607962 8912849 89128...,1.875,"[3.0, 2.625, 1.125, 1.875, 3.0, 2.75, 1.25, 2.0]"
54,4607958,8728799,[4607957 4607958 4607964 4607963 8912850 89128...,1.875,"[2.625, 1.875, 0.375, 1.125, 2.75, 1.875, 0.5,..."
55,4607962,8728803,[4607961 4607962 4607968 4607967 8912854 89128...,1.875,"[2.625, 1.875, 0.375, 1.125, 2.75, 2.0, 0.5, 1..."
58,4608164,8728999,[4608157 4608158 4608164 4608163 8913050 89130...,1.125,"[3.0, 2.625, 1.125, 2.25, 3.0, 2.75, 1.25, 2.125]"
59,4608165,8729000,[4608158 4608159 4608165 4608164 8913051 89130...,0.375,"[2.625, 1.875, 0.375, 1.125, 2.75, 2.0, 0.5, 1..."